// Auto-generated comment analysis data
const COMMENT_DASHBOARD_DATA = {
    daily_summaries: [
  {
    "date": "2024-04-30",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-05-02",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-05-03",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-05-04",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-05-06",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-05-08",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-05-12",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-05-14",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-05-16",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-05-18",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-05-23",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-05-30",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-06-04",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-06-07",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-06-10",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-06-24",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-07-03",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-07-09",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-07-28",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-08-09",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-08-13",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-08-14",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-08-19",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-08-20",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-08-21",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-08-23",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-08-24",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-08-27",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-09-05",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-09-12",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-09-14",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-10-15",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-11-06",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-11-07",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-11-15",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-11-17",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-12-02",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-12-13",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-12-15",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2024-12-23",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-01-19",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-02-23",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-03-16",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-05-22",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-05-24",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-06-14",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-06-16",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-06-17",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-07-08",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-07-24",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-08-06",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-08-08",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-08-11",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-08-13",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-08-16",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-08-18",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-08-20",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-08-22",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-08-23",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-08-26",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-08-29",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-09-01",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-09-16",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-09-25",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-09-26",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-09-27",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-09-30",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-10-07",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-10-19",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-10-23",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-11-02",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-11-16",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-12-04",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-12-07",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-12-13",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2025-12-14",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-01-21",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-01-23",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-01-30",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-02-06",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-02-09",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-06",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-07",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-09",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-10",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-11",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-12",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-14",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-15",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-16",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-17",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-18",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-19",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-20",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-21",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-22",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-23",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-24",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-25",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-26",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-27",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-28",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-29",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-30",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-03-31",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-01",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-02",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-03",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-04",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-05",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-06",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-07",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-08",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-09",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-10",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-11",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-12",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-13",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-14",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-15",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-16",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-17",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-18",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-19",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-20",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-21",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-22",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-23",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-24",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-25",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-26",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-27",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-28",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-29",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-04-30",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-01",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-02",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-03",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-04",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-05",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-06",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-07",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-08",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-09",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-10",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-11",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-12",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-13",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-14",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-15",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-16",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-17",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-18",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-19",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-20",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-21",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-22",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-23",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-24",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-25",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-26",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-27",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-28",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-29",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-30",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-05-31",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-01",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-02",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-03",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-04",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-05",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-06",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-07",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-08",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-09",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-10",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-11",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-12",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-13",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-14",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-15",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-16",
    "total_posts_with_comments": 2,
    "total_comments": 10,
    "total_replies": 6,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 2
  },
  {
    "date": "2026-06-17",
    "total_posts_with_comments": 13,
    "total_comments": 49,
    "total_replies": 14,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 1,
    "neutral_count": 12
  },
  {
    "date": "2026-06-18",
    "total_posts_with_comments": 7,
    "total_comments": 16,
    "total_replies": 8,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 1,
    "neutral_count": 6
  },
  {
    "date": "2026-06-19",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-20",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-21",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-22",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-23",
    "total_posts_with_comments": 1,
    "total_comments": 2,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 1
  },
  {
    "date": "2026-06-24",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-25",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-26",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-27",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-28",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-29",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-06-30",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-07-01",
    "total_posts_with_comments": 7,
    "total_comments": 27,
    "total_replies": 8,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 7
  },
  {
    "date": "2026-07-02",
    "total_posts_with_comments": 4,
    "total_comments": 9,
    "total_replies": 2,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 4
  },
  {
    "date": "2026-07-03",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-07-04",
    "total_posts_with_comments": 2,
    "total_comments": 7,
    "total_replies": 2,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 2
  },
  {
    "date": "2026-07-05",
    "total_posts_with_comments": 4,
    "total_comments": 9,
    "total_replies": 2,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 4
  },
  {
    "date": "2026-07-06",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-07-07",
    "total_posts_with_comments": 3,
    "total_comments": 12,
    "total_replies": 4,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 3
  },
  {
    "date": "2026-07-08",
    "total_posts_with_comments": 1,
    "total_comments": 6,
    "total_replies": 4,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 1
  },
  {
    "date": "2026-07-09",
    "total_posts_with_comments": 1,
    "total_comments": 1,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 1
  },
  {
    "date": "2026-07-10",
    "total_posts_with_comments": 1,
    "total_comments": 2,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 1
  },
  {
    "date": "2026-07-11",
    "total_posts_with_comments": 0,
    "total_comments": 0,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 0
  },
  {
    "date": "2026-07-12",
    "total_posts_with_comments": 4,
    "total_comments": 9,
    "total_replies": 2,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 4
  },
  {
    "date": "2026-07-13",
    "total_posts_with_comments": 1,
    "total_comments": 4,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 1,
    "neutral_count": 0
  },
  {
    "date": "2026-07-14",
    "total_posts_with_comments": 2,
    "total_comments": 10,
    "total_replies": 4,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 2
  },
  {
    "date": "2026-07-15",
    "total_posts_with_comments": 2,
    "total_comments": 4,
    "total_replies": 2,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 2
  },
  {
    "date": "2026-07-16",
    "total_posts_with_comments": 4,
    "total_comments": 4,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 4
  },
  {
    "date": "2026-07-17",
    "total_posts_with_comments": 2,
    "total_comments": 5,
    "total_replies": 3,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 2
  },
  {
    "date": "2026-07-18",
    "total_posts_with_comments": 3,
    "total_comments": 7,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 3
  },
  {
    "date": "2026-07-19",
    "total_posts_with_comments": 4,
    "total_comments": 7,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 1,
    "agreement_count": 0,
    "neutral_count": 3
  },
  {
    "date": "2026-07-20",
    "total_posts_with_comments": 1,
    "total_comments": 2,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 1
  },
  {
    "date": "2026-07-21",
    "total_posts_with_comments": 7,
    "total_comments": 31,
    "total_replies": 7,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 7
  },
  {
    "date": "2026-07-22",
    "total_posts_with_comments": 3,
    "total_comments": 9,
    "total_replies": 1,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 2,
    "neutral_count": 1
  },
  {
    "date": "2026-07-23",
    "total_posts_with_comments": 6,
    "total_comments": 17,
    "total_replies": 2,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 2,
    "neutral_count": 4
  },
  {
    "date": "2026-07-24",
    "total_posts_with_comments": 8,
    "total_comments": 22,
    "total_replies": 8,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 8
  },
  {
    "date": "2026-07-25",
    "total_posts_with_comments": 5,
    "total_comments": 16,
    "total_replies": 6,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 1,
    "neutral_count": 4
  },
  {
    "date": "2026-07-26",
    "total_posts_with_comments": 7,
    "total_comments": 24,
    "total_replies": 9,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 7
  },
  {
    "date": "2026-07-27",
    "total_posts_with_comments": 3,
    "total_comments": 5,
    "total_replies": 1,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 3
  },
  {
    "date": "2026-07-28",
    "total_posts_with_comments": 4,
    "total_comments": 7,
    "total_replies": 1,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 4
  },
  {
    "date": "2026-07-29",
    "total_posts_with_comments": 2,
    "total_comments": 4,
    "total_replies": 1,
    "rejection_count": 1,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 1
  },
  {
    "date": "2026-07-30",
    "total_posts_with_comments": 7,
    "total_comments": 20,
    "total_replies": 8,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 1,
    "neutral_count": 6
  },
  {
    "date": "2026-07-31",
    "total_posts_with_comments": 4,
    "total_comments": 6,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 1,
    "agreement_count": 1,
    "neutral_count": 2
  },
  {
    "date": "2026-08-01",
    "total_posts_with_comments": 6,
    "total_comments": 11,
    "total_replies": 1,
    "rejection_count": 0,
    "defense_count": 1,
    "agreement_count": 0,
    "neutral_count": 5
  },
  {
    "date": "2026-08-02",
    "total_posts_with_comments": 8,
    "total_comments": 13,
    "total_replies": 4,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 8
  },
  {
    "date": "2026-08-03",
    "total_posts_with_comments": 1,
    "total_comments": 1,
    "total_replies": 0,
    "rejection_count": 0,
    "defense_count": 0,
    "agreement_count": 0,
    "neutral_count": 1
  }
],
    top_controversial_posts: [
  {
    "post_id": "15365",
    "title": "[질문] 와이번 죽었을때 부활은 어디서 시켜야하나요 [8]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15365",
    "date": "2026-06-17",
    "views": 1579,
    "recommends": 0,
    "total_comments": 8,
    "reply_count": 5,
    "post_sentiment": 0,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.0,
    "controversy_score": 90
  },
  {
    "post_id": "15361",
    "title": "[잡담] 절벽도약 쿠쿠새 [7]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15361",
    "date": "2026-06-16",
    "views": 936,
    "recommends": 0,
    "total_comments": 7,
    "reply_count": 5,
    "post_sentiment": 0,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.0,
    "controversy_score": 85
  },
  {
    "post_id": "6700",
    "title": "질문이 있습니다!!",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6700",
    "date": "2026-07-01",
    "views": 119,
    "recommends": 0,
    "total_comments": 8,
    "reply_count": 4,
    "post_sentiment": 0,
    "comment_sentiment": 0.12,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": -0.12,
    "controversy_score": 80
  },
  {
    "post_id": "15698",
    "title": "[잡담] 초보자 질문몇가지입니다. [7]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15698",
    "date": "2026-07-21",
    "views": 264,
    "recommends": 0,
    "total_comments": 7,
    "reply_count": 4,
    "post_sentiment": -1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": -1.0,
    "controversy_score": 75
  },
  {
    "post_id": "15366",
    "title": "[잡담] 설마 1,000시간 하신분은 없으시겠죠?? [7]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15366",
    "date": "2026-06-17",
    "views": 5833,
    "recommends": 2,
    "total_comments": 7,
    "reply_count": 4,
    "post_sentiment": 0,
    "comment_sentiment": -0.14,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.14,
    "controversy_score": 75
  },
  {
    "post_id": "6720",
    "title": "행님들 이게임 장비시스템 질문이요!",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6720",
    "date": "2026-07-08",
    "views": 227,
    "recommends": 0,
    "total_comments": 6,
    "reply_count": 4,
    "post_sentiment": 0,
    "comment_sentiment": 0.33,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": -0.33,
    "controversy_score": 70
  },
  {
    "post_id": "15755",
    "title": "[잡담] 드디어드디어 어비스 다깼다!!ㅠ [6]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15755",
    "date": "2026-07-30",
    "views": 747,
    "recommends": 3,
    "total_comments": 6,
    "reply_count": 4,
    "post_sentiment": 0,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.0,
    "controversy_score": 70
  },
  {
    "post_id": "15723",
    "title": "[잡담] 이제 슬슬 데미안으로 하는 챕터인데요 [7]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15723",
    "date": "2026-07-24",
    "views": 628,
    "recommends": 1,
    "total_comments": 7,
    "reply_count": 3,
    "post_sentiment": 0,
    "comment_sentiment": 0.14,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": -0.14,
    "controversy_score": 65
  },
  {
    "post_id": "6701",
    "title": "이건 뭐에요?",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6701",
    "date": "2026-07-01",
    "views": 116,
    "recommends": 0,
    "total_comments": 6,
    "reply_count": 3,
    "post_sentiment": 0,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.0,
    "controversy_score": 60
  },
  {
    "post_id": "6719",
    "title": "마격 한번 부탁드리겠습니다",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6719",
    "date": "2026-07-07",
    "views": 99,
    "recommends": 0,
    "total_comments": 6,
    "reply_count": 3,
    "post_sentiment": 0,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.0,
    "controversy_score": 60
  },
  {
    "post_id": "15720",
    "title": "[잡담] 8장 피의대관식 하는중인데요 [5]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15720",
    "date": "2026-07-24",
    "views": 156,
    "recommends": 0,
    "total_comments": 5,
    "reply_count": 3,
    "post_sentiment": 0,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.0,
    "controversy_score": 55
  },
  {
    "post_id": "15736",
    "title": "[스샷] 화염속성 무기 야망의 철퇴 패치되서 얻기 쉬워짐 [5]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15736",
    "date": "2026-07-26",
    "views": 642,
    "recommends": 0,
    "total_comments": 5,
    "reply_count": 3,
    "post_sentiment": 0,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.0,
    "controversy_score": 55
  },
  {
    "post_id": "15727",
    "title": "[잡담] 기계일꾼으로 캠프자원 자동화시스템 돌려버리니.. [5]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15727",
    "date": "2026-07-25",
    "views": 839,
    "recommends": 1,
    "total_comments": 5,
    "reply_count": 3,
    "post_sentiment": 1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 1.0,
    "controversy_score": 55
  },
  {
    "post_id": "6733",
    "title": "모든 도전과제를 달성했습니다.",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6733",
    "date": "2026-07-14",
    "views": 209,
    "recommends": 0,
    "total_comments": 6,
    "reply_count": 2,
    "post_sentiment": 0,
    "comment_sentiment": 0.17,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": -0.17,
    "controversy_score": 50
  },
  {
    "post_id": "15367",
    "title": "[잡담] 어비스 다섯개 남았는데 접근 방법 [6]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15367",
    "date": "2026-06-17",
    "views": 1272,
    "recommends": 1,
    "total_comments": 6,
    "reply_count": 2,
    "post_sentiment": 0,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.0,
    "controversy_score": 50
  },
  {
    "post_id": "15734",
    "title": "[질문] ps5pro hdr 최대휘도 뭘로 해야되는건가요?ㅠㅠ [4]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15734",
    "date": "2026-07-26",
    "views": 457,
    "recommends": 0,
    "total_comments": 4,
    "reply_count": 3,
    "post_sentiment": 0,
    "comment_sentiment": -0.25,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.25,
    "controversy_score": 50
  },
  {
    "post_id": "15699",
    "title": "[잡담] 잊혀진 장군의묘 보스 [7]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15699",
    "date": "2026-07-21",
    "views": 436,
    "recommends": 0,
    "total_comments": 7,
    "reply_count": 1,
    "post_sentiment": 0,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.0,
    "controversy_score": 45
  },
  {
    "post_id": "15751",
    "title": "[잡담] 벨로스 잡으려면 냉기저항15필수인가요? [5]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15751",
    "date": "2026-07-30",
    "views": 341,
    "recommends": 0,
    "total_comments": 5,
    "reply_count": 2,
    "post_sentiment": 0,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.0,
    "controversy_score": 45
  },
  {
    "post_id": "6704",
    "title": "마격 부탁드립니다~",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6704",
    "date": "2026-07-02",
    "views": 172,
    "recommends": 0,
    "total_comments": 4,
    "reply_count": 2,
    "post_sentiment": 0,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.0,
    "controversy_score": 40
  },
  {
    "post_id": "6734",
    "title": "마격 부탁드립니다",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6734",
    "date": "2026-07-14",
    "views": 164,
    "recommends": 0,
    "total_comments": 4,
    "reply_count": 2,
    "post_sentiment": 0,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.0,
    "controversy_score": 40
  },
  {
    "post_id": "15363",
    "title": "[질문] 봉쇄지역은 용병미션 필수인가요? [4]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15363",
    "date": "2026-06-17",
    "views": 980,
    "recommends": 0,
    "total_comments": 4,
    "reply_count": 2,
    "post_sentiment": 0,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.0,
    "controversy_score": 40
  },
  {
    "post_id": "15752",
    "title": "[잡담] 원소와 쿠쿠새 무기는 언제 얻을 수 있나요? [4]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15752",
    "date": "2026-07-30",
    "views": 233,
    "recommends": 0,
    "total_comments": 4,
    "reply_count": 2,
    "post_sentiment": 1,
    "comment_sentiment": 0.25,
    "discrepancy_label": "동조 (Agreement - Pos)",
    "discrepancy_score": 0.75,
    "controversy_score": 40
  },
  {
    "post_id": "6708",
    "title": "1.13 패치노트",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6708",
    "date": "2026-07-04",
    "views": 1113,
    "recommends": 0,
    "total_comments": 5,
    "reply_count": 1,
    "post_sentiment": -1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": -1.0,
    "controversy_score": 35
  },
  {
    "post_id": "6747",
    "title": "장비 질문",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6747",
    "date": "2026-07-17",
    "views": 112,
    "recommends": 0,
    "total_comments": 3,
    "reply_count": 2,
    "post_sentiment": 0,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.0,
    "controversy_score": 35
  },
  {
    "post_id": "15382",
    "title": "[잡담] 쿠쿠새 방어구에 들어가는 갑옷재료는 다시는 구매못하네요 [3]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15382",
    "date": "2026-06-18",
    "views": 1326,
    "recommends": 1,
    "total_comments": 3,
    "reply_count": 2,
    "post_sentiment": 0,
    "comment_sentiment": -0.67,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.67,
    "controversy_score": 35
  },
  {
    "post_id": "15379",
    "title": "[잡담] 예전 게임 녹화된거 보다보니 데미니스에 적들 바글바글 엄청 많을때가 [3]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15379",
    "date": "2026-06-18",
    "views": 1186,
    "recommends": 0,
    "total_comments": 3,
    "reply_count": 2,
    "post_sentiment": 0,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.0,
    "controversy_score": 35
  },
  {
    "post_id": "15376",
    "title": "[질문] 철가면감옥 열쇠 질문입니다. [3]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15376",
    "date": "2026-06-18",
    "views": 5447,
    "recommends": 2,
    "total_comments": 3,
    "reply_count": 2,
    "post_sentiment": 0,
    "comment_sentiment": -0.33,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.33,
    "controversy_score": 35
  },
  {
    "post_id": "15732",
    "title": "[질문] 아 스콜라스톤 선행퀘안뜨네요ㅜ [3]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15732",
    "date": "2026-07-26",
    "views": 414,
    "recommends": 0,
    "total_comments": 3,
    "reply_count": 2,
    "post_sentiment": 0,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.0,
    "controversy_score": 35
  },
  {
    "post_id": "6711",
    "title": "마격부탁드립니다",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6711",
    "date": "2026-07-05",
    "views": 175,
    "recommends": 0,
    "total_comments": 4,
    "reply_count": 1,
    "post_sentiment": 0,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.0,
    "controversy_score": 30
  },
  {
    "post_id": "15709",
    "title": "[질문] 어비스 동력핵 박힌거 뽑는법 헬프 ㅡ사진첨부ㅡ [4]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15709",
    "date": "2026-07-23",
    "views": 508,
    "recommends": 0,
    "total_comments": 4,
    "reply_count": 1,
    "post_sentiment": 0,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 0.0,
    "controversy_score": 30
  }
],
    top_discrepancy_posts: [
  {
    "post_id": "6758",
    "title": "검사만 햇는대요",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6758",
    "date": "2026-07-19",
    "views": 89,
    "recommends": 0,
    "total_comments": 2,
    "reply_count": 0,
    "post_sentiment": -1,
    "comment_sentiment": 1.0,
    "discrepancy_label": "반박 (Defense)",
    "discrepancy_score": -2.0,
    "controversy_score": 10
  },
  {
    "post_id": "15744",
    "title": "[잡담] 133시간 플레이 하면서 느낀 가장 필요한 기능 [2]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15744",
    "date": "2026-07-29",
    "views": 519,
    "recommends": 0,
    "total_comments": 2,
    "reply_count": 1,
    "post_sentiment": 1,
    "comment_sentiment": -0.5,
    "discrepancy_label": "반발 (Rejection)",
    "discrepancy_score": 1.5,
    "controversy_score": 20
  },
  {
    "post_id": "15757",
    "title": "[질문] 지정신장 이거 버그인가요 [2]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15757",
    "date": "2026-07-31",
    "views": 269,
    "recommends": 0,
    "total_comments": 2,
    "reply_count": 0,
    "post_sentiment": -1,
    "comment_sentiment": 0.5,
    "discrepancy_label": "반박 (Defense)",
    "discrepancy_score": -1.5,
    "controversy_score": 10
  },
  {
    "post_id": "6785",
    "title": "패치 노트 1.16",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6785",
    "date": "2026-08-01",
    "views": 306,
    "recommends": 0,
    "total_comments": 4,
    "reply_count": 0,
    "post_sentiment": -1,
    "comment_sentiment": 0.25,
    "discrepancy_label": "반박 (Defense)",
    "discrepancy_score": -1.25,
    "controversy_score": 20
  },
  {
    "post_id": "6695",
    "title": "아니 메인퀘스트 다 밀었는데 이거 맞냐...",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6695",
    "date": "2026-07-01",
    "views": 74,
    "recommends": 0,
    "total_comments": 2,
    "reply_count": 0,
    "post_sentiment": 1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 1.0,
    "controversy_score": 10
  },
  {
    "post_id": "6708",
    "title": "1.13 패치노트",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6708",
    "date": "2026-07-04",
    "views": 1113,
    "recommends": 0,
    "total_comments": 5,
    "reply_count": 1,
    "post_sentiment": -1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": -1.0,
    "controversy_score": 35
  },
  {
    "post_id": "6712",
    "title": "버그인가? 업뎃 1.13 적용후!",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6712",
    "date": "2026-07-05",
    "views": 287,
    "recommends": 0,
    "total_comments": 1,
    "reply_count": 0,
    "post_sentiment": -1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": -1.0,
    "controversy_score": 5
  },
  {
    "post_id": "6717",
    "title": "1시간차 뉴비 질문입니다!!",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6717",
    "date": "2026-07-07",
    "views": 183,
    "recommends": 0,
    "total_comments": 3,
    "reply_count": 0,
    "post_sentiment": 0,
    "comment_sentiment": 1.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": -1.0,
    "controversy_score": 15
  },
  {
    "post_id": "6722",
    "title": "기억의파편-붉은사막-흔적-옛채석장 안되는 분들",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6722",
    "date": "2026-07-09",
    "views": 133,
    "recommends": 0,
    "total_comments": 1,
    "reply_count": 0,
    "post_sentiment": 0,
    "comment_sentiment": -1.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 1.0,
    "controversy_score": 5
  },
  {
    "post_id": "6745",
    "title": "1.14 패치 노트",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6745",
    "date": "2026-07-16",
    "views": 171,
    "recommends": 0,
    "total_comments": 1,
    "reply_count": 0,
    "post_sentiment": -1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": -1.0,
    "controversy_score": 5
  },
  {
    "post_id": "6750",
    "title": "낚시 질문 드립니다.",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6750",
    "date": "2026-07-18",
    "views": 129,
    "recommends": 0,
    "total_comments": 2,
    "reply_count": 0,
    "post_sentiment": -1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": -1.0,
    "controversy_score": 10
  },
  {
    "post_id": "6757",
    "title": "붉은사막 퍼즐기믹은 개씹망작중 역대 개망작임.",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6757",
    "date": "2026-07-19",
    "views": 148,
    "recommends": 0,
    "total_comments": 3,
    "reply_count": 0,
    "post_sentiment": 1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 1.0,
    "controversy_score": 15
  },
  {
    "post_id": "15698",
    "title": "[잡담] 초보자 질문몇가지입니다. [7]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15698",
    "date": "2026-07-21",
    "views": 264,
    "recommends": 0,
    "total_comments": 7,
    "reply_count": 4,
    "post_sentiment": -1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": -1.0,
    "controversy_score": 75
  },
  {
    "post_id": "15697",
    "title": "[잡담] 상자 무한 버그? [3]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15697",
    "date": "2026-07-21",
    "views": 1730,
    "recommends": 3,
    "total_comments": 3,
    "reply_count": 1,
    "post_sentiment": -1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": -1.0,
    "controversy_score": 25
  },
  {
    "post_id": "15706",
    "title": "[잡담] ATAG 타고 레이져 난사 너무 재밌는데 [2]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15706",
    "date": "2026-07-22",
    "views": 383,
    "recommends": 0,
    "total_comments": 2,
    "reply_count": 1,
    "post_sentiment": 1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 1.0,
    "controversy_score": 20
  },
  {
    "post_id": "15722",
    "title": "[정보] 붉은사막 패치 노트 버전 1.15.00, 알려진 문제점(7/24) [1]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15722",
    "date": "2026-07-24",
    "views": 250,
    "recommends": 1,
    "total_comments": 1,
    "reply_count": 0,
    "post_sentiment": -1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": -1.0,
    "controversy_score": 5
  },
  {
    "post_id": "15716",
    "title": "[잡담] 이제 시작합니다 이게임 [2]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15716",
    "date": "2026-07-24",
    "views": 457,
    "recommends": 0,
    "total_comments": 2,
    "reply_count": 0,
    "post_sentiment": 1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 1.0,
    "controversy_score": 10
  },
  {
    "post_id": "6775",
    "title": "그래픽에 대한 거 질문 점여",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6775",
    "date": "2026-07-26",
    "views": 286,
    "recommends": 0,
    "total_comments": 3,
    "reply_count": 0,
    "post_sentiment": -1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": -1.0,
    "controversy_score": 15
  },
  {
    "post_id": "6770",
    "title": "울산 왁뿌볼 파는곳",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6770",
    "date": "2026-07-24",
    "views": 344,
    "recommends": 0,
    "total_comments": 1,
    "reply_count": 0,
    "post_sentiment": 1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 1.0,
    "controversy_score": 5
  },
  {
    "post_id": "15733",
    "title": "[소감] 플래티넘 트로피 획득했습니다! [4]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15733",
    "date": "2026-07-26",
    "views": 2095,
    "recommends": 4,
    "total_comments": 4,
    "reply_count": 1,
    "post_sentiment": 1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 1.0,
    "controversy_score": 30
  },
  {
    "post_id": "15729",
    "title": "[질문] 말이 현상수배범 싫어해요 [4]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15729",
    "date": "2026-07-25",
    "views": 621,
    "recommends": 1,
    "total_comments": 4,
    "reply_count": 1,
    "post_sentiment": -1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": -1.0,
    "controversy_score": 30
  },
  {
    "post_id": "15727",
    "title": "[잡담] 기계일꾼으로 캠프자원 자동화시스템 돌려버리니.. [5]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15727",
    "date": "2026-07-25",
    "views": 839,
    "recommends": 1,
    "total_comments": 5,
    "reply_count": 3,
    "post_sentiment": 1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 1.0,
    "controversy_score": 55
  },
  {
    "post_id": "15753",
    "title": "[잡담] 도박할때 나는 올인했는데 상대방은 올인없이 그냥 패까는경우 [1]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15753",
    "date": "2026-07-30",
    "views": 207,
    "recommends": 0,
    "total_comments": 1,
    "reply_count": 0,
    "post_sentiment": -1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": -1.0,
    "controversy_score": 5
  },
  {
    "post_id": "15750",
    "title": "[잡담] 무기,갑옷류 안팔았는데 자꾸 사라지네요 [1]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15750",
    "date": "2026-07-30",
    "views": 252,
    "recommends": 0,
    "total_comments": 1,
    "reply_count": 0,
    "post_sentiment": 0,
    "comment_sentiment": -1.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": 1.0,
    "controversy_score": 5
  },
  {
    "post_id": "15764",
    "title": "[정보] [정보] 붉은사막 패치 노트 버전 1.16.00 (08/01) [1]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15764",
    "date": "2026-08-01",
    "views": 1266,
    "recommends": 3,
    "total_comments": 1,
    "reply_count": 0,
    "post_sentiment": -1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": -1.0,
    "controversy_score": 5
  },
  {
    "post_id": "15765",
    "title": "[질문] 에세리온 핵 정화가 안됩니다 ㅜㅜ [3]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15765",
    "date": "2026-08-01",
    "views": 204,
    "recommends": 0,
    "total_comments": 3,
    "reply_count": 1,
    "post_sentiment": -1,
    "comment_sentiment": 0.0,
    "discrepancy_label": "중립 (Neutral)",
    "discrepancy_score": -1.0,
    "controversy_score": 25
  },
  {
    "post_id": "6731",
    "title": "신규유저인데 어비스 아티펙트 노가다",
    "source": "inven",
    "url": "https://www.inven.co.kr/board/crimson/6246/6731",
    "date": "2026-07-13",
    "views": 156,
    "recommends": 0,
    "total_comments": 4,
    "reply_count": 0,
    "post_sentiment": 1,
    "comment_sentiment": 0.25,
    "discrepancy_label": "동조 (Agreement - Pos)",
    "discrepancy_score": 0.75,
    "controversy_score": 20
  },
  {
    "post_id": "15356",
    "title": "[잡담] 습득 불가 지식 정리 [4]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15356",
    "date": "2026-06-17",
    "views": 1057,
    "recommends": 1,
    "total_comments": 4,
    "reply_count": 0,
    "post_sentiment": -1,
    "comment_sentiment": -0.25,
    "discrepancy_label": "동조 (Agreement - Neg)",
    "discrepancy_score": -0.75,
    "controversy_score": 20
  },
  {
    "post_id": "15728",
    "title": "[잡담] 혹시..이거 버그인가요? [4]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15728",
    "date": "2026-07-25",
    "views": 415,
    "recommends": 0,
    "total_comments": 4,
    "reply_count": 1,
    "post_sentiment": -1,
    "comment_sentiment": -0.25,
    "discrepancy_label": "동조 (Agreement - Neg)",
    "discrepancy_score": -0.75,
    "controversy_score": 30
  },
  {
    "post_id": "15752",
    "title": "[잡담] 원소와 쿠쿠새 무기는 언제 얻을 수 있나요? [4]",
    "source": "ruliweb",
    "url": "https://bbs.ruliweb.com/family/5614/board/185595/read/15752",
    "date": "2026-07-30",
    "views": 233,
    "recommends": 0,
    "total_comments": 4,
    "reply_count": 2,
    "post_sentiment": 1,
    "comment_sentiment": 0.25,
    "discrepancy_label": "동조 (Agreement - Pos)",
    "discrepancy_score": 0.75,
    "controversy_score": 40
  }
],
    top_best_comments: [
  {
    "comment_id": "68925",
    "author": "Kyungminzi",
    "created_at": "2026-07-21 09:24:00",
    "content": "플탐 기준 레데리2>붉사>위쳐3>엘든링 ㅋㅋ",
    "recommends": 2,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "15696",
    "source": "ruliweb",
    "post_title": "[잡담] 엘든링>붉사>레데리>위처3 [4]"
  },
  {
    "comment_id": "67882",
    "author": "안젤리나 다닐로바",
    "created_at": "2026-06-18 14:32:00",
    "content": "캐릭터를 함께 데리고 다니는 법은 알고 계시죠? 일단 내가 움직이는 캐릭터를 잠긴 문 앞에 두고 그 캐릭터의 시점을 문 반대로 두고 이리 저리 움직이면 같이 데리고 다니던 동료는 순간 이동(?) 같은 것을 합니다. 대충 해보시면 이해가 될 겁니다. 그러다 보면 감옥 안에서 텔레포트 하는 경우가 생깁니다. 그럴때 바로 안에 있는 동료로 바꿔주고 문을 따버리면 됩니다. 안에서는 문이 자동으로 따지더라고요.",
    "recommends": 2,
    "dislikes": 0,
    "is_reply": "1",
    "parent_comment_id": "67851",
    "sentiment": 0,
    "post_id": "15376",
    "source": "ruliweb",
    "post_title": "[질문] 철가면감옥 열쇠 질문입니다. [3]"
  },
  {
    "comment_id": "67798",
    "author": "흰색갈기",
    "created_at": "2026-06-17 01:56:00",
    "content": "설정에서 재봉쇄 빈도 조절한다음에 공헌도 상점에 가서 15포인트 소비하면 다시 못털게 할 수 있어요",
    "recommends": 2,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "15363",
    "source": "ruliweb",
    "post_title": "[질문] 봉쇄지역은 용병미션 필수인가요? [4]"
  },
  {
    "comment_id": "69047",
    "author": "루리웹-0659335948",
    "created_at": "2026-07-25 12:09:00",
    "content": "기억에는 바깥쪽으로 나가서 기계들 다 부서서 저 %게이지 다 줄이는거였나..싶음",
    "recommends": 2,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "15730",
    "source": "ruliweb",
    "post_title": "[질문] 고드릭을 장악한 기계 제거하기 [1]"
  },
  {
    "comment_id": "19894",
    "author": "사실난배추",
    "created_at": "2026-07-07 20:20:15",
    "content": "1. PC라 저는 모르겠습니다 ㅠㅠ 2. 단검 검 양손검 도끼 등등 숙련도 같은건 없습니다~ 덧. 환도? 유튜브 검색해서 드시는거 추천, 황금사과 + 금광석 으로 금괴 제작 하셔서 은화 없어서 뭐도 못 하는 경험은 없으셨으면 합니다 ㅠ0ㅠ 벌금 낼 돈도 읍스....ㅠㅠ 나머지는 자유롭게~ 즐기세요~",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 1,
    "post_id": "6717",
    "source": "inven",
    "post_title": "1시간차 뉴비 질문입니다!!"
  },
  {
    "comment_id": "19919",
    "author": "Mungtigi",
    "created_at": "2026-07-12 13:33:08",
    "content": "열쇠 없을거예요 배 들어 올려서 밑으로 들어 가야 될거예요.",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "6728",
    "source": "inven",
    "post_title": "해안가 이 배 잠긴문 열쇠 어디서 구하나요??"
  },
  {
    "comment_id": "19945",
    "author": "Unluckynpc",
    "created_at": "2026-07-16 17:55:21",
    "content": "예전에 데미안 신속장전이 특정챕터에서 배우지 않고 넘어가면 영구적으로 배우는게 불가능해져서 보고 배우는 기술도 어비스를 소모해서 배우는게 가능해져서 초기화시 같이 리셋되도록 바뀌었나봄?",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "6740",
    "source": "inven",
    "post_title": "보고배우기로 스킬 배우고난뒤 초기화하면 다시 배워야하나요?"
  },
  {
    "comment_id": "68931",
    "author": "Jn.bgddgm",
    "created_at": "2026-07-21 11:58:00",
    "content": "저랑 정확히 정반대시네. 위쳐3>레데리2>붉사>엘든링",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "15696",
    "source": "ruliweb",
    "post_title": "[잡담] 엘든링>붉사>레데리>위처3 [4]"
  },
  {
    "comment_id": "68957",
    "author": "하니르N",
    "created_at": "2026-07-21 21:06:00",
    "content": "일종의 너무 빠른 진행을 막기 위한 장치죠. 톱니바퀴 재능을 가진 동료가 들어와야 진행이 가능한 퀘스트 입니다. 퀘스트가 어느정도 더 진행되어야 새로운 동료를 영입할수 있을겁니다.",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "15703",
    "source": "ruliweb",
    "post_title": "[질문] 용병 임무보내기 퀘스트가 실행이 되지 않습니다. [2]"
  },
  {
    "comment_id": "68962",
    "author": "Christina21",
    "created_at": "2026-07-21 23:00:00",
    "content": "뒤늦게 사서 한게 후회됨. 하는 내내 '펄 어비스 대체 뭘 만든거야' 이생각이 든다는",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "15704",
    "source": "ruliweb",
    "post_title": "[잡담] 붉사 예구해놓고 아직까지 손도 못대고 있는데 조언 부탁드립니다. [4]"
  },
  {
    "comment_id": "68964",
    "author": "니말이무조건옳습니다",
    "created_at": "2026-07-22 07:27:00",
    "content": "시간이 있다 지금 플레이 하고 스토리 업뎃 하면 2회차 시간이 없다 기다렸다 스토리 업뎃후 즐긴다 많이 바꼈습니다 초기 버전이랑 많이 달라요",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "15704",
    "source": "ruliweb",
    "post_title": "[잡담] 붉사 예구해놓고 아직까지 손도 못대고 있는데 조언 부탁드립니다. [4]"
  },
  {
    "comment_id": "68972",
    "author": "ØгヲгんıØг",
    "created_at": "2026-07-22 14:23:00",
    "content": "이런 얘기는 처음 들어보네요 ㅎㅎ 재미는 사람마다 느끼는게 다르고 취향도 다른데 ㅎㅎ 저는 처음부터 재밌었음.",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 1,
    "post_id": "15707",
    "source": "ruliweb",
    "post_title": "[질문] 초반퀘 어느정도지나야 재밌어지나요? [5]"
  },
  {
    "comment_id": "67860",
    "author": "시호랑",
    "created_at": "2026-06-18 08:38:00",
    "content": "ㅜㅜ 생각해보니 그재료로 사용한거였네요 답변주셔서 감사합니다 ㅜ 근데조금 아쉽네요 콜렉터(?) 입장에서는 다 갖고있고싶은데ㅠ",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": -1,
    "post_id": "15382",
    "source": "ruliweb",
    "post_title": "[잡담] 쿠쿠새 방어구에 들어가는 갑옷재료는 다시는 구매못하네요 [3]"
  },
  {
    "comment_id": "67861",
    "author": "Barack Obama",
    "created_at": "2026-06-18 09:56:00",
    "content": "저는 아직 제작안했는데 나중에 패치로 재구매 가능하게 해주지않을까여 ㅠㅠ",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "1",
    "parent_comment_id": "67860",
    "sentiment": 0,
    "post_id": "15382",
    "source": "ruliweb",
    "post_title": "[잡담] 쿠쿠새 방어구에 들어가는 갑옷재료는 다시는 구매못하네요 [3]"
  },
  {
    "comment_id": "67862",
    "author": "시호랑",
    "created_at": "2026-06-18 10:17:00",
    "content": "그니까요ㅜ 우리같은 콜렉터들을 위해(?)!!",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "1",
    "parent_comment_id": "67860",
    "sentiment": -1,
    "post_id": "15382",
    "source": "ruliweb",
    "post_title": "[잡담] 쿠쿠새 방어구에 들어가는 갑옷재료는 다시는 구매못하네요 [3]"
  },
  {
    "comment_id": "67886",
    "author": "라트라다",
    "created_at": "2026-06-18 15:23:00",
    "content": "헬우드 요새가 점령 당한 뒤 거기에 있는 고블린들 싸우다보면 나옵니다. 세이브 로드 신공이 필요하지만요.",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "1",
    "parent_comment_id": "67866",
    "sentiment": 0,
    "post_id": "15377",
    "source": "ruliweb",
    "post_title": "[잡담] 드뎌 조악한 리시의 신발 획득. [3]"
  },
  {
    "comment_id": "67852",
    "author": "루리웹-3074055515",
    "created_at": "2026-06-17 21:42:00",
    "content": "클리프 지정타 회복으로도 될걸요. 말 강장제인가 그것도 회복됨요.",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "15375",
    "source": "ruliweb",
    "post_title": "[잡담] 말이.맛이 갔는데 [3]"
  },
  {
    "comment_id": "67853",
    "author": "호레기",
    "created_at": "2026-06-17 22:12:00",
    "content": "마굿간 가면 치료도 됩니다",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "15375",
    "source": "ruliweb",
    "post_title": "[잡담] 말이.맛이 갔는데 [3]"
  },
  {
    "comment_id": "67856",
    "author": "5236235",
    "created_at": "2026-06-17 23:48:00",
    "content": "저도 너덜너덜 해져서 첨에 몰랐는데 지정타 치유 때리면 살아납니디ㅣ",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "15375",
    "source": "ruliweb",
    "post_title": "[잡담] 말이.맛이 갔는데 [3]"
  },
  {
    "comment_id": "67847",
    "author": "jenon83",
    "created_at": "2026-06-17 20:23:00",
    "content": "가구배치하는 메뉴에서 집변경이라는게 있었군요. 찾았습니다!",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "15373",
    "source": "ruliweb",
    "post_title": "[질문] 혹시 집을 증축하는 방법 같은게 있나요? [1]"
  },
  {
    "comment_id": "67840",
    "author": "미남오징어",
    "created_at": "2026-06-17 15:59:00",
    "content": "어떤 스킬을 쓰시려는지 모르겠지만 당연히 쓸려고하는 스킬을 배우지 않으면 못 씁니다. 스킬마다 설명이랑 미리보기 가능하니 쓰려고 하는 콤보 스킬에 해당 스킬을 배웠는지 확인해보세요",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "15372",
    "source": "ruliweb",
    "post_title": "[잡담] 스킬을 다찍지않으면 콤보가 안나갈수있나요? [1]"
  },
  {
    "comment_id": "67815",
    "author": "뭐살까^^",
    "created_at": "2026-06-17 11:47:00",
    "content": "데메니스 의상점에서 파는 \"대지의 명예\" 세트",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "15368",
    "source": "ruliweb",
    "post_title": "[질문] 데미안 복장 관련 질문 좀 드립니다. [3]"
  },
  {
    "comment_id": "67829",
    "author": "레전드홀더",
    "created_at": "2026-06-17 14:00:00",
    "content": "모든 게임이 그렇긴하죠.붉사만큼 탐험의 재미가 있는 게임은 없겠지만...",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "1",
    "parent_comment_id": "67827",
    "sentiment": 0,
    "post_id": "15366",
    "source": "ruliweb",
    "post_title": "[잡담] 설마 1,000시간 하신분은 없으시겠죠?? [7]"
  },
  {
    "comment_id": "67825",
    "author": "YooHJ",
    "created_at": "2026-06-17 13:09:00",
    "content": "피뢰침 퀘할때 번개 맞고 죽어버리던데",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "1",
    "parent_comment_id": "67816",
    "sentiment": 0,
    "post_id": "15365",
    "source": "ruliweb",
    "post_title": "[질문] 와이번 죽었을때 부활은 어디서 시켜야하나요 [8]"
  },
  {
    "comment_id": "67801",
    "author": "뭐살까^^",
    "created_at": "2026-06-17 07:56:00",
    "content": "724.6 ㄷㄷㄷ",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "15364",
    "source": "ruliweb",
    "post_title": "[잡담] 으앙 강제 은퇴네요 [5]"
  },
  {
    "comment_id": "67806",
    "author": "냐옹갈기용병",
    "created_at": "2026-06-17 09:44:00",
    "content": "저는 이동하거나 말탈때 앞으로 밀고있으면 엄지에 통증이 있습니다. 자동달리기 옵션같은거 있었으면..ㅡㅜ",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "15364",
    "source": "ruliweb",
    "post_title": "[잡담] 으앙 강제 은퇴네요 [5]"
  },
  {
    "comment_id": "67828",
    "author": "W1K7X8",
    "created_at": "2026-06-17 13:17:00",
    "content": "헐 제대로 즐기셨네요 그래도 건강이 최우선이니 쉬어가시지요",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "15364",
    "source": "ruliweb",
    "post_title": "[잡담] 으앙 강제 은퇴네요 [5]"
  },
  {
    "comment_id": "67848",
    "author": "오렉게",
    "created_at": "2026-06-17 21:09:00",
    "content": "아마존에서 손가락 부목 사서 끼고 주무세요 ㅠ",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "15364",
    "source": "ruliweb",
    "post_title": "[잡담] 으앙 강제 은퇴네요 [5]"
  },
  {
    "comment_id": "67893",
    "author": "젠장또당신입니까",
    "created_at": "2026-06-18 17:10:00",
    "content": "전 그래서 비싸긴 하지만 듀센엣지를 쓴답니다.... 백버튼으로 대신하니 훨씬 편안",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "0",
    "parent_comment_id": "",
    "sentiment": 0,
    "post_id": "15364",
    "source": "ruliweb",
    "post_title": "[잡담] 으앙 강제 은퇴네요 [5]"
  },
  {
    "comment_id": "67864",
    "author": "흰색갈기",
    "created_at": "2026-06-18 11:32:00",
    "content": "얼마전에 패치로 보호 요청 추가됬어요",
    "recommends": 1,
    "dislikes": 0,
    "is_reply": "1",
    "parent_comment_id": "67798",
    "sentiment": 0,
    "post_id": "15363",
    "source": "ruliweb",
    "post_title": "[질문] 봉쇄지역은 용병미션 필수인가요? [4]"
  }
]
};
