name: Build and Deploy Blog

on:
  push:
    branches:
      - main
    paths:
      - '_posts/**'
      - 'build_post.py'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build HTML Posts
        run: python build_post.py
        
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-build HTML from new markdown posts"
          file_pattern: 'posts/ insights/ sitemap.xml index.html'
